name: rstcheck

# CINTENT >> MANUAL_TRIGGER
# Run this workflow every time a new commit pushed to your repository
# on: [push, pull_request]
on: [repository_dispatch, workflow_dispatch]

jobs:
  rstcheck:
    name: Doc Check
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        # CINTENT >> CHANGE_VERSION
        # uses: actions/checkout@v2
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      
      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
        with:
          nonblocking: true

      - name: Install Python dependencies
        run: |
          python -m pip install rstcheck[sphinx]

      - name: Run rstcheck
        run: |
          rstcheck -r --ignore-messages autoclass --ignore-directives autofunction .

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
